-- Database Schema for Adaptive Learning Prototype (Demo Robust Version)

-- Users table
CREATE TABLE users (
    id TEXT PRIMARY KEY, -- e.g., 'learner_example_com'
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL DEFAULT 'pass123',
    role TEXT CHECK (role IN ('learner', 'tutor')) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Sessions table
CREATE TABLE session_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    login_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    logout_at TIMESTAMP WITH TIME ZONE
);

-- Behavior Events table
CREATE TABLE behavior_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    event_type TEXT NOT NULL,
    metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Alerts table
CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    alert_type TEXT NOT NULL,
    message TEXT,
    is_resolved BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Control Actions table
CREATE TABLE control_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tutor_id TEXT,
    learner_id TEXT,
    action_type TEXT NOT NULL,
    new_mode TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- Initial Mock Data
-- Note: UUIDs will be generated by the app or during insert. 
-- For the prototype, we expect user emails to be the primary identifier in logic.
